server:
  port: 9595
  servlet:
    context-path: /user-management-app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql20apr2021
    url: jdbc:mysql://localhost:3306/user_management
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp


  mail:
    host: smtp.gmail.com
    password: Sagar${1202}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: sagarkmohapatra2012@gmail.com          

app:
  messages:
     invalidCredentials: Invalid Credentials
     accountLocked: Your Account is Locked
     loginSuccess: Welcome To Ashok IT.....
     regSuccess: Successfully registered, Please check your registered email to unlock account
     regFail: something went wrong please try again !!!
     forgotPwdSuccess: we have sent password on your registered email-id
     forgotPwdFail: We can't find a user with that e-mail address
     userNotFound: We can't find a user with this id
     unlockSuccess: Account Unlocked, please proceed with login
     unlockFail: Please Enter the Registered email id & correct Temporary Password provided in the registered mail id
     EmailBodyGenerationFailExceptionMsg: Problem Occured While Generating Email Body, Please try again later!!!
     
     
     
     
     
     
     
     