server:
  port: 9595
  servlet:
    context-path: /user-management-app
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mysql20apr2021
    url: jdbc:mysql://localhost:3306/user_management
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp


  mail:
    host: smtp.gmail.com
    password: Sagar${1202}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000
    username: sagarkmohapatra2012@gmail.com          

app:
  messages:
     invalidCredentials: INVALID CREDENTIALS
     accountLocked: YOUR ACCOUNT IS LOCKED
     loginSuccess: WELCOME TO ASHOK IT.....
     regSuccess: SUCCESSFULLY REGISTERED, PLEASE CHECK YOUR REGISTERED EMAIL TO UNLOCK ACCOUNT
     regFail: SOMETHING WENT WRONG PLEASE TRY AGAIN !!!
     forgotPwdSuccess: WE HAVE SENT PASSWORD ON YOUR REGISTERED EMAIL-ID
     forgotPwdFail: WE CAN'T FIND A USER WITH THAT E-MAIL ADDRESS
     userNotFound: NO USER FOUND WITH ID   
     unlockSuccess: ACCOUNT UNLOCKED, PLEASE PROCEED WITH LOGIN
     unlockFail: PLEASE ENTER THE REGISTERED EMAIL ID & CORRECT TEMPORARY PASSWORD PROVIDED IN THE REGISTERED MAIL ID
     EmailBodyGenerationFailExceptionMsg: PROBLEM OCCURED WHILE GENERATING EMAIL BODY, PLEASE TRY AGAIN LATER!!!
     
     
     
     
     
     
     
     